export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const TODOS = 'todos';
export const FETCH_TODOS = 'FETCH_TODOS';
export const SUCCES_TODOS = 'SUCCES_TODOS';
export const ADD_TODO_SUCCES = 'ADD_TODO_SUCCES';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';

export const SIGN_IN_FETCH = 'SIGN_IN_FETCH';
export const SIGN_IN_SUCCES = 'SIGN_IN_SUCCES';
export const SIGN_OUT_FETCH = 'SIGN_OUT_FETCH';
export const SIGN_OUT_SUCCES = 'SIGN_OUT_SUCCES';

export const SIGN_IN_FETCH_PASSWORD = 'SIGN_IN_FETCH_PASSWORD';
export const SIGN_IN_SUCCES_PASSWORD = 'SIGN_IN_SUCCES_PASSWORD';

export const SIGN_IN_FETCH_AUTHORIZATION = 'SIGN_IN_FETCH_AUTHORIZATION';
export const SIGN_IN_SUCCES_AUTHORIZATION = 'SIGN_IN_SUCCES_AUTHORIZATION';

